"""Add metadata fields to Link model

Revision ID: 01621136f527
Revises: e4ba0d2042d1
Create Date: 2025-12-30 23:40:38.072928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01621136f527'
down_revision = 'e4ba0d2042d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.drop_column('image_url')
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
