"""add slack workspace model

Revision ID: 0d5802781b3b
Revises: 1b0c73ed9886
Create Date: 2026-01-01 23:53:59.623120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d5802781b3b'
down_revision = '1b0c73ed9886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.create_table('slack_workspaces',
        sa.Column('team_id', sa.String(length=50), nullable=False),
        sa.Column('team_name', sa.String(length=200), nullable=True),
        sa.Column('bot_token', sa.String(length=200), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id', name='pk_slack_workspaces'),
        sa.UniqueConstraint('team_id', name='uq_slack_workspaces_team_id')
        )
    except:
        pass
    with op.batch_alter_table('slack_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key('fk_slack_users_team_id', 'slack_workspaces', ['team_id'], ['team_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slack_users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_slack_users_team_id', type_='foreignkey')
        batch_op.drop_column('team_id')

    op.drop_table('slack_workspaces')
    # ### end Alembic commands ###
