"""empty message

Revision ID: 794b1cdc0f54
Revises: e4ba0d2042d1
Create Date: 2025-12-30 18:08:05.847969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '794b1cdc0f54'
down_revision = 'e4ba0d2042d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('path_editor_bridge',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('path_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['paths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'path_id')
    )
    with op.batch_alter_table('bookmark_lists', schema=None) as batch_op:
        batch_op.alter_column('path_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_plan', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('subscription_plan')

    with op.batch_alter_table('bookmark_lists', schema=None) as batch_op:
        batch_op.alter_column('path_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('path_editor_bridge')
    # ### end Alembic commands ###
