"""Add linkversity fields to user

Revision ID: afbf65aa806f
Revises: 8fab015ce57d
Create Date: 2026-04-22 19:29:09.545087

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "afbf65aa806f"
down_revision = "8fab015ce57d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_tokens",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_tokens", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_tokens_token_hash"), ["token_hash"], unique=True
        )

    # Note: paths.team_id foreign key to enterprise_teams may not exist in this migration
    # Skip it if the table/column doesn't exist

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("last_password_change", sa.DateTime(), nullable=True)
        )
        batch_op.alter_column(
            "email", existing_type=sa.VARCHAR(length=120), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "email", existing_type=sa.VARCHAR(length=120), nullable=True
        )
        batch_op.drop_column("last_password_change")

    # Note: paths.team_id foreign key to enterprise_teams may not exist in this migration
    # Skip it if the table/column doesn't exist

    with op.batch_alter_table("user_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_tokens_token_hash"))

    op.drop_table("user_tokens")
    # ### end Alembic commands ###
