"""add api_token to user

Revision ID: c02c419b258a
Revises: 01621136f527
Create Date: 2026-01-01 22:45:18.238199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c02c419b258a'
down_revision = '01621136f527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_token', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('uq_user_api_token', ['api_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_api_token', type_='unique')
        batch_op.drop_column('api_token')

    # ### end Alembic commands ###
