"""empty message

Revision ID: d12ac2be19df
Revises: 7994bf89d156
Create Date: 2025-02-13 12:02:02.865027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd12ac2be19df'
down_revision = '7994bf89d156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('path_editor_bridge',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('path_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['paths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'path_id')
    )
    # op.drop_table('users_old')
    # with op.batch_alter_table('bookmark_list_user_bridge', schema=None) as batch_op:
    #     # batch_op.drop_constraint(None, type_='foreignkey')
    #     # batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # with op.batch_alter_table('like_list_user_bridge', schema=None) as batch_op:
    #     # batch_op.drop_constraint(None, type_='foreignkey')
    #     # batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # with op.batch_alter_table('paths', schema=None) as batch_op:
    #     # batch_op.drop_constraint(None, type_='foreignkey')
    #     # batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # with op.batch_alter_table('role_user_bridge', schema=None) as batch_op:
    #     # batch_op.drop_constraint(None, type_='foreignkey')
    #     # batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('_password',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('emoji_class',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text("'em-airplane'"))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.alter_column('emoji_class',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'em-airplane'"))
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('_password',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('role_user_bridge', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users_old', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('paths', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users_old', ['user_id'], ['id'])

    with op.batch_alter_table('like_list_user_bridge', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users_old', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('bookmark_list_user_bridge', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users_old', ['user_id'], ['id'], ondelete='CASCADE')

    op.create_table('users_old',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.TEXT(), nullable=True),
    sa.Column('_password', sa.TEXT(), nullable=True),
    sa.Column('first_name', sa.TEXT(), nullable=True),
    sa.Column('last_name', sa.TEXT(), nullable=True),
    sa.Column('is_admin', sa.NUMERIC(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('date_registered', sa.NUMERIC(), nullable=True),
    sa.Column('is_email_confirmed', sa.NUMERIC(), nullable=True),
    sa.Column('email_confirm_date', sa.NUMERIC(), nullable=True),
    sa.Column('emoji_class', sa.TEXT(), nullable=True),
    sa.Column('subscription_plan', sa.INTEGER(), nullable=True)
    )
    op.drop_table('path_editor_bridge')
    # ### end Alembic commands ###
