"""empty message

Revision ID: e4ba0d2042d1
Revises: d12ac2be19df
Create Date: 2025-12-30 10:56:11.848318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4ba0d2042d1'
down_revision = 'd12ac2be19df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TABLE IF EXISTS _alembic_tmp_bookmark_lists')
    
    op.execute('DELETE FROM bookmark_lists WHERE path_id IS NULL')
    with op.batch_alter_table('bookmark_lists', schema=None) as batch_op:
        batch_op.alter_column('path_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_plan', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('subscription_plan')

    with op.batch_alter_table('bookmark_lists', schema=None) as batch_op:
        batch_op.alter_column('path_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
